# Password
DEFAULT_SALT_SIZE = 32
HASH_ITERATIONS_AMOUNT = 100000
HASH_RESULT_SIZE = 64

DISTANCE_GRANUALITY = 45

ADMIN_MAIL = "smart.authentication.project@gmail.com"
ADMIN_PASSWORD = "Ss112233"

MAX_FAILED_LOGIN_ATTEMPTS = 4
